# Generated by Django 5.2.8 on 2025-11-08 09:21

import app_products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_products", "0002_productimage_productvariantimage_vendorproduct"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="main_image",
            field=models.ImageField(
                default="products/main/0_default_product.jpg",
                upload_to=app_products.models.product_main_image_upload_path,
            ),
        ),
    ]
