# Generated by Django 5.2.8 on 2025-11-08 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_products", "0003_alter_product_main_image"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="attributevalue",
            unique_together=set(),
        ),
    ]
