# Generated by Django 5.2.8 on 2025-11-08 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_products", "0004_alter_attributevalue_unique_together"),
    ]

    operations = [
        migrations.CreateModel(
            name="Currency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="ISO code, e.g., USD, EUR, IRR",
                        max_length=3,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "symbol",
                    models.CharField(
                        blank=True,
                        help_text="Currency symbol like $, €, ﷼",
                        max_length=5,
                    ),
                ),
                (
                    "exchange_rate",
                    models.DecimalField(
                        decimal_places=6,
                        default=1.0,
                        help_text="Exchange rate relative to the base currency (optional)",
                        max_digits=12,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name_plural": "Currencies",
                "ordering": ["code"],
            },
        ),
        migrations.AddField(
            model_name="vendorproduct",
            name="currency",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="vendor_products",
                to="app_products.currency",
            ),
        ),
    ]
