# Generated by Django 5.2.8 on 2025-11-08 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_products", "0006_alter_vendorproduct_currency"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vendorproduct",
            name="currency",
        ),
        migrations.AddField(
            model_name="productvariant",
            name="currency",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="vendor_products",
                to="app_products.currency",
            ),
            preserve_default=False,
        ),
    ]
