# Generated by Django 5.2.8 on 2025-11-08 06:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_accounts", "0002_user_is_customer_user_is_vendor"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendor",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2025, 11, 8, 6, 41, 12, 60891, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="vendor",
            name="is_active",
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
