# Generated by Django 5.2.8 on 2025-11-09 07:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("app_products", "0007_remove_vendorproduct_currency_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PricingRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the pricing rule (e.g. 'Black Friday 10% off').",
                        max_length=255,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Optional description or notes for internal reference.",
                    ),
                ),
                (
                    "min_cart_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Minimum total cart value required for this rule to apply (optional).",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "min_category_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Minimum total category value required if this rule targets a specific category (optional).",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "rule_type",
                    models.CharField(
                        choices=[
                            ("cart_percentage", "Cart - Percentage"),
                            ("cart_fixed", "Cart - Fixed amount"),
                            ("category_percentage", "Category - Percentage"),
                            ("category_fixed", "Category - Fixed amount"),
                            ("product_percentage", "Product - Percentage"),
                            ("product_fixed", "Product - Fixed amount"),
                        ],
                        help_text="Defines how the rule applies (cart-level, category-level, or product-level).",
                        max_length=32,
                    ),
                ),
                (
                    "discount_percentage",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Discount percentage (0–100). Used for percentage-based rules.",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Fixed discount amount (e.g., $10 off). Used for fixed-value rules.",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "coupon_code",
                    models.CharField(
                        blank=True,
                        help_text="Coupon code for manual application. Leave blank for automatic rules.",
                        max_length=64,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "starts_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date and time when this rule becomes active (optional).",
                        null=True,
                    ),
                ),
                (
                    "ends_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date and time when this rule expires (optional).",
                        null=True,
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=True,
                        help_text="Determines whether the rule is currently enabled.",
                    ),
                ),
                (
                    "max_global_uses",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Maximum total number of times this rule can be used across all users.",
                        null=True,
                    ),
                ),
                (
                    "usage_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Tracks how many times this rule has been used (auto-updated on each usage).",
                    ),
                ),
                (
                    "per_user_limit",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Maximum times a single user can use this rule (null = unlimited).",
                        null=True,
                    ),
                ),
                (
                    "user_usage",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Per-user usage tracking: {'user_id': count}",
                    ),
                ),
                (
                    "combinable",
                    models.BooleanField(
                        default=False,
                        help_text="If True, this rule can be combined with other discounts in the same cart.",
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        db_index=True,
                        default=0,
                        help_text="Higher values indicate higher priority when multiple rules are active.",
                    ),
                ),
                (
                    "max_discount_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Maximum discount amount this rule can apply (optional).",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when this rule was created.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp of the last modification to this rule.",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("USD", "US Dollar"),
                            ("EUR", "Euro"),
                            ("GBP", "Pound"),
                            ("IRR", "Iranian Rial"),
                        ],
                        help_text="If be empty for all pricing rule will applied on each currency.",
                        max_length=3,
                        null=True,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        help_text="If the rule applies to a specific category, set it here.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="app_products.category",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this rule (optional).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_pricing_rules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="It will only apply to a specific customer",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assigned_pricing_rules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Pricing Rule",
                "verbose_name_plural": "Pricing Rules",
                "ordering": ["-priority", "starts_at"],
            },
        ),
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "session_key",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "currency",
                    models.ForeignKey(
                        help_text="Currency in which this cart operates (matches product variant currency).",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="carts",
                        to="app_products.currency",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="carts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "pricing_rule",
                    models.ForeignKey(
                        blank=True,
                        help_text="Applied discount or pricing rule, if any.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="carts",
                        to="app_cart.pricingrule",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CartItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "cart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="app_cart.cart",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cart_items",
                        to="app_products.productvariant",
                    ),
                ),
            ],
            options={
                "unique_together": {("cart", "variant")},
            },
        ),
    ]
