# Generated by Django 5.2.8 on 2025-11-09 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_cart", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cart",
            name="pricing_rule",
        ),
        migrations.AddField(
            model_name="cart",
            name="pricing_rules",
            field=models.ManyToManyField(
                blank=True,
                help_text="All applied pricing rules or coupons for this cart.",
                related_name="carts",
                to="app_cart.pricingrule",
            ),
        ),
    ]
