# Generated by Django 5.2.8 on 2025-11-09 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_cart", "0002_remove_cart_pricing_rule_cart_pricing_rules"),
    ]

    operations = [
        migrations.AddField(
            model_name="pricingrule",
            name="auto_apply",
            field=models.BooleanField(
                default=False,
                help_text="Apply automatically if no coupon code is provided.",
            ),
        ),
    ]
