# Generated by Django 5.2.8 on 2025-11-09 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_cart", "0003_pricingrule_auto_apply"),
    ]

    operations = [
        migrations.AddField(
            model_name="pricingrule",
            name="max_cart_value",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Maximum cart value for this rule to apply (optional). For tiered discounts.",
                max_digits=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="pricingrule",
            name="min_cart_value",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Minimum total cart value required for this rule to apply (optional).",
                max_digits=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="pricingrule",
            name="min_category_value",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Minimum total category value required if this rule targets a specific category (optional).",
                max_digits=20,
                null=True,
            ),
        ),
    ]
